### ISSUE TITLE
Raspberry Pi compile and wallet usage - TEMP

### ISSUE THREAD

**Issue by BKdilse** [The-GNTL-Project/gntl#13]
Provided by @woody and @yin.  Need to move into Readme and maybe wallet part into wiki:

Raspberry pi install gntl wallet instructiuons

Tested on raspberry pi2b and pi 400 using official os raspbian buster armhf (32bit). This should work on all pi3's and pi4's including compute modules untested though but pretty sure it will work.

This will not work on pi64 os or by adding arm_64bit in config.txt in boot at present working progress.

First we need to update glibc as the current raspbian system only has 2.28 while min 2.29 is needed.  This will not update the whole system as this will run the gntl wallet in closed system as it could cause issues with raspiban os and related software etc.

Instructions for glibc
sudo apt install gawk bison -y
wget http://ftp.gnu.org/gnu/glibc/glibc-2.33.tar.gz
tar -xf glibc-2.33.tar.gz
rm -r glibc-2.33.tar.gz
cd glibc-2.33
mkdir build
cd build
../configure --prefix=$home
make -j4 (change -j4 to appropriate number related to your thread count)

wait a while for it to build

wallet instructions
Please make sure you get the armv7 version at present the armv8 wont work on 64bit os or  arm_64bit in config.txt in boot

wget https://gntl.cash/downloads/GNTL-v0.1.0.1-arm-linux-gnueabihf.tar.gz
tar -xf GNTL-v0.1.0.1-arm-linux-gnueabihf.tar.gz
rm -r GNTL-v0.1.0.1-arm-linux-gnueabihf.tar.gz
cd GNTL-arm-linux-gnueabihf
mv GNTL-arm-linux-gnueabihf gntl (renames file for easy typing later on)

To run the wallet you need to run it in the glibc container we just built.

cd glibc-2.33/build
sudo ./testrun.sh ~/gntl/gntld --data-dir /gntl   (please make sure data-dir is not on a small sd card)

First time update blockchain will take a while depending on what storage your using. Please wait till this complete syncs up before you carry on to wallet.

Open another command prompt while leaving the above 

sudo ./testrun.sh ~/gntl/gntl-wallet-cli

Done

**Comment by woodycal** [comment]
../configure �prefix=$home suppose to be ../configure --prefix=$home

**Comment by santost12** [comment]
yin here. I thought I'd point this out and say that the "--prefix=$HOME" option isn't needed but doesn't hurt anything. You do not need to recompile if you already built it. (Just don't run any make install !) We aren't installing it to user's home(nor the system). It's a habit for me to always include the prefix option when compiling.

**Comment by yin** [comment]
... Yeah... I was wondering, what's going on here.

**Comment by BKdilse** [comment]
Added to Development branch, will be merge later.
