### ISSUE TITLE
Typo in source code comments

### ISSUE THREAD

**Issue by sudoebm** [The-GNTL-Project/gntl#15]
Files such as key_stream.h show our copyright as "// Copyright (c) 2018-201@, The GNTL Project"
[key_stream.txt](https://github.com/The-GNTL-Project/gntl/files/6408659/key_stream.txt)

**Comment by BKdilse** [comment]
Well spotted !  You one that competition 💯

**Comment by BKdilse** [comment]
Fixed in dev branch: https://github.com/The-GNTL-Project/gntl/commit/25d07c1901c0d8ca622507fcfcb1da3481fb9312
