### ISSUE TITLE
Build Errors - Ubuntu 21.04 VM

### ISSUE THREAD

**Issue by thomascookandroid** [The-GNTL-Project/gntl#31]
Error:

```
[ 71%] Building CXX object src/gntl_mq/CMakeFiles/obj_gntl_mq.dir/gntlMQ.cpp.o
In file included from /home/osboxes/Desktop/Crypto/Repos/gntl/src/cryptonote_core/blockchain.h:36,
                 from /home/osboxes/Desktop/Crypto/Repos/gntl/src/cryptonote_core/cryptonote_core.h:46,
                 from /home/osboxes/Desktop/Crypto/Repos/gntl/src/gntl_mq/zmq_handler.h:36,
                 from /home/osboxes/Desktop/Crypto/Repos/gntl/src/gntl_mq/gntlMQ.h:65,
                 from /home/osboxes/Desktop/Crypto/Repos/gntl/src/gntl_mq/gntlMQ.cpp:46:
/usr/include/boost/serialization/list.hpp: In function ‘void boost::serialization::load(Archive&, std::__cxx11::list<U, Allocator>&, unsigned int)’:
/usr/include/boost/serialization/list.hpp:53:33: error: ‘library_version_type’ in namespace ‘boost::serialization’ does not name a type; did you mean ‘item_version_type’?
   53 |     const boost::serialization::library_version_type library_version(
      |                                 ^~~~~~~~~~~~~~~~~~~~
      |                                 item_version_type
/usr/include/boost/serialization/list.hpp:60:30: error: ‘library_version_type’ is not a member of ‘boost::serialization’; did you mean ‘item_version_type’?
   60 |     if(boost::serialization::library_version_type(3) < library_version){
      |                              ^~~~~~~~~~~~~~~~~~~~
      |                              item_version_type
/usr/include/boost/serialization/list.hpp:60:56: error: ‘library_version’ was not declared in this scope; did you mean ‘SSLeay_version’?
   60 |     if(boost::serialization::library_version_type(3) < library_version){
      |                                                        ^~~~~~~~~~~~~~~
      |                                                        SSLeay_version
make[3]: *** [src/gntl_mq/CMakeFiles/obj_gntl_mq.dir/build.make:82: src/gntl_mq/CMakeFiles/obj_gntl_mq.dir/gntlMQ.cpp.o] Error 1
make[3]: Leaving directory '/home/osboxes/Desktop/Crypto/Repos/gntl/build/release'
make[2]: *** [CMakeFiles/Makefile2:1795: src/gntl_mq/CMakeFiles/obj_gntl_mq.dir/all] Error 2
make[2]: Leaving directory '/home/osboxes/Desktop/Crypto/Repos/gntl/build/release'
make[1]: *** [Makefile:160: all] Error 2
make[1]: Leaving directory '/home/osboxes/Desktop/Crypto/Repos/gntl/build/release'
make: *** [Makefile:88: release] Error 2
```

I'm running windows, but for development purposes I spin up linux VM for ease of tooling, because let's be honest windows + complex linux oriented development sucks!

Anyway, I followed the documentation for how to get gntl building here: https://github.com/The-GNTL-Project/gntl and receive the above error log when attempting the build.

Steps to reproduce:

- For exact replication, use the osbox VM image, version 21.04 from here: https://www.osboxes.org/ubuntu/
- Starting with fresh image
- `sudo apt-get install cmake`
- `sudo apt-get install gcc`
- `sudo apt-get install libboost-all-dev`
- `sudo apt update && sudo apt install --yes git build-essential curl pkg-config libssl-dev libsodium-dev libunwind-dev liblzma-dev libreadline-dev libldns-dev libexpat1-dev doxygen graphviz libudev-dev libusb-1.0-0-dev libhidapi-dev xsltproc gperf autoconf automake libtool-bin libunbound-dev miniupnpc libevent-dev libzmq5-dev`
- `sudo apt install -y libgtest-dev && cd /usr/src/gtest && sudo cmake . && sudo make && sudo mv libg* /usr/lib/`
- `git clone --recursive https://github.com/The-GNTL-Project/gntl`
- `cd gntl && git checkout master && USE_SINGLE_BUILDDIR=1 make release`
- Observe error log above

**Comment by BKdilse** [comment]
> Error:
> 
> ```
> [ 71%] Building CXX object src/gntl_mq/CMakeFiles/obj_gntl_mq.dir/gntlMQ.cpp.o
> In file included from /home/osboxes/Desktop/Crypto/Repos/gntl/src/cryptonote_core/blockchain.h:36,
>                  from /home/osboxes/Desktop/Crypto/Repos/gntl/src/cryptonote_core/cryptonote_core.h:46,
>                  from /home/osboxes/Desktop/Crypto/Repos/gntl/src/gntl_mq/zmq_handler.h:36,
>                  from /home/osboxes/Desktop/Crypto/Repos/gntl/src/gntl_mq/gntlMQ.h:65,
>                  from /home/osboxes/Desktop/Crypto/Repos/gntl/src/gntl_mq/gntlMQ.cpp:46:
> /usr/include/boost/serialization/list.hpp: In function ‘void boost::serialization::load(Archive&, std::__cxx11::list<U, Allocator>&, unsigned int)’:
> /usr/include/boost/serialization/list.hpp:53:33: error: ‘library_version_type’ in namespace ‘boost::serialization’ does not name a type; did you mean ‘item_version_type’?
>    53 |     const boost::serialization::library_version_type library_version(
>       |                                 ^~~~~~~~~~~~~~~~~~~~
>       |                                 item_version_type
> /usr/include/boost/serialization/list.hpp:60:30: error: ‘library_version_type’ is not a member of ‘boost::serialization’; did you mean ‘item_version_type’?
>    60 |     if(boost::serialization::library_version_type(3) < library_version){
>       |                              ^~~~~~~~~~~~~~~~~~~~
>       |                              item_version_type
> /usr/include/boost/serialization/list.hpp:60:56: error: ‘library_version’ was not declared in this scope; did you mean ‘SSLeay_version’?
>    60 |     if(boost::serialization::library_version_type(3) < library_version){
>       |                                                        ^~~~~~~~~~~~~~~
>       |                                                        SSLeay_version
> make[3]: *** [src/gntl_mq/CMakeFiles/obj_gntl_mq.dir/build.make:82: src/gntl_mq/CMakeFiles/obj_gntl_mq.dir/gntlMQ.cpp.o] Error 1
> make[3]: Leaving directory '/home/osboxes/Desktop/Crypto/Repos/gntl/build/release'
> make[2]: *** [CMakeFiles/Makefile2:1795: src/gntl_mq/CMakeFiles/obj_gntl_mq.dir/all] Error 2
> make[2]: Leaving directory '/home/osboxes/Desktop/Crypto/Repos/gntl/build/release'
> make[1]: *** [Makefile:160: all] Error 2
> make[1]: Leaving directory '/home/osboxes/Desktop/Crypto/Repos/gntl/build/release'
> make: *** [Makefile:88: release] Error 2
> ```
> 
> I'm running windows, but for development purposes I spin up linux VM for ease of tooling, because let's be honest windows + complex linux oriented development sucks!
> 
> Anyway, I followed the documentation for how to get gntl building here: https://github.com/The-GNTL-Project/gntl and receive the above error log when attempting the build.
> 
> Steps to reproduce:
> 
> * For exact replication, use the osbox VM image, version 21.04 from here: https://www.osboxes.org/ubuntu/
> * Starting with fresh image
> * `sudo apt-get install cmake`
> * `sudo apt-get install gcc`
> * `sudo apt-get install libboost-all-dev`
> * `sudo apt update && sudo apt install --yes git build-essential curl pkg-config libssl-dev libsodium-dev libunwind-dev liblzma-dev libreadline-dev libldns-dev libexpat1-dev doxygen graphviz libudev-dev libusb-1.0-0-dev libhidapi-dev xsltproc gperf autoconf automake libtool-bin libunbound-dev miniupnpc libevent-dev libzmq5-dev`
> * `sudo apt install -y libgtest-dev && cd /usr/src/gtest && sudo cmake . && sudo make && sudo mv libg* /usr/lib/`
> * `git clone --recursive https://github.com/The-GNTL-Project/gntl`
> * `cd gntl && git checkout master && USE_SINGLE_BUILDDIR=1 make release`
> * Observe error log above

Are you able to try this again, using the updated instructions, tested on 18.04 and 20.04 ?
Will save me installed a 21.04 VM.

**Comment by BKdilse** [comment]
No update on this.
