### ISSUE TITLE
How to withdraw to an exchange?

### ISSUE THREAD

**Issue by alexgabbard01** [The-GNTL-Project/gntl#47]
CLI's and all the complexities that will make your head spin, I just want to to withdraw my mined GNTL coins to xeggexx exchange and I'm really having a hard time doing that. i tried this command
transfer xeggexWalletAddress 200
The coins never arrives to the destination address. When I type "help transfer"  (without quotes) on CLI wallet i see
"Command usage:
transfer [index=<N1>[,<N2>,...]] [<priority] [<ring_size>] (<URI> | <address> <amount>) [<payment_id>]"

I really don't need all that junk, I'm used to having to supply a destination address and required amount when using other QT wallets, not this complicated junk that almost no one needs.

**Comment by BKdilse** [comment]
1st of off, Issues is for real issues with the release, not for support.  Use Discord: https://discord.gg/4HyVA2A

**transfer ADDRESS AMOUNT** is all you need.  I've used it personally, and it works fine.
I don't see any issues here.
